version: "3.8"
services:
  activemq:
    image: rmohr/activemq:latest
    ports:
      - "61616:61616" # JMS port
      - "61613:61613" # JMS port
      - "8161:8161" # Web Console
    volumes:
      - ./docker/activemq_data:/data
