version: '3'
services:
  redis:
    container_name: python-rate-limiter-redis
    image: redis:7.2.5
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - python-rate-limiter-network

volumes:
  redis_data:

networks:
  python-rate-limiter-network:
    driver: bridge