REDIS_HOST_ENV = 'REDIS_HOST'
REDIS_PORT_ENV = 'REDIS_PORT'
REDIS_DB_ENV = 'REDIS_DB'

ACTIVEMQ_HOST_ENV = 'ACTIVEMQ_HOST'
ACTIVEMQ_PORT_ENV = 'ACTIVEMQ_PORT'
ACTIVEMQ_QUEUE_ENV = 'ACTIVEMQ_QUEUE'


## env variables
RATE_LIMITER_ALGORITHM_ENV = 'RATE_LIMITER_ALGORITHM'
MASTER_NODE_ENV = 'MASTER_NODE'